clc
clear
close all;
%%
% Auto-generated by MATLAB on 20-Jul-2020 20:24:55
feat_comb_data = [];

 load feat_td_eg2_dat.mat
 feat_comb_data = [feat_comb_data feats_data];
 load feat_td_mav4_dat.mat
 feat_comb_data = [feat_comb_data feats_data];
%
load feat_eg_pdg_04_dat
feat_comb_data = [feat_comb_data feats_data];
load train_class_label_NP52.mat
trainingData = [feat_comb_data train_cl_vec];

Npat = size(trainingData,1);
MC = 100;
%  MC = 10
for kx = 1:MC
r_index = ShuffleSequence(Npat);
% Extract predictors and response
predictors = trainingData(r_index,1:end-1);
response = trainingData(r_index,end);

c = cvpartition(response,'k',10);
opts = statset('display','iter');
fun = @(XT,yT,Xt,yt)...
      (knnPredictor(Xt,yt,XT,yT));

[fs,history] = sequentialfs(fun,predictors,response,'cv',c,'options',opts);
% Nfold = 10;
% spread = 1.0;
% fldaflag = 0;
% 
% [sel_feats,sel_kappa] = mySequentialFS2(Feat_data(:,1:10),labelvec2,Nfold,spread,fldaflag);
sfname = sprintf('sel_feat_knn_%.2d',kx);
save(sfname,'fs');
clear fs
clear r_index;
clear predictors;
clear response;
end

