clc;
clear all;
close all;
k = 0:1:6;
x(k == 0) = 9;
x(k == 1) = 4;
x(k == 2) = 1;
x(k == 3) = 0;
x(k == 4) = 1;
x(k == 5) = 4;
x(k == 6) = 9;
N = length(x);
% k = 0:1:N-1;
subplot(3,1,1);
stem(x,'linewidth',2.5);
n0=3;
k=0:1:6;
% xn = ifft(x,N);
x1 = ifft(x,N);
% xn = ifftshift(x1);
basis= exp((-i*2*pi*k*n0)/N);
% disp('op seq xn');
xn = x1.*basis;
disp('op seq x1');
disp(x1);
disp('op seq xn');
disp(xn);
